framework:
    messenger:
        transports:
            async_email: '%env(MESSENGER_TRANSPORT_DSN)%/email_dispatch_queue'
            sync: 'sync://'
        routing:
            # Async queues
            'App\Shared\Domain\Mail\Message\MailMessage': async_email
            # Sync queues
            'App\Auth\Domain\Message\CreateUserMessage': sync
            'App\Auth\Domain\Message\SendActivationTokenMessage': sync
