app_login:
    path: /
    controller: App\Auth\Infrastructure\Controller\AuthController::login

app_register:
    path: /register
    controller: App\Auth\Infrastructure\Controller\AuthController::register